# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculator.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from turtle import screensize
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(371, 513)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.outPutLabel = QtWidgets.QLabel(self.centralwidget)
        self.outPutLabel.setGeometry(QtCore.QRect(10, 10, 351, 50))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.outPutLabel.setFont(font)
        self.outPutLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.outPutLabel.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.outPutLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.outPutLabel.setObjectName("outPutLabel")
        self.percentButton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda:self.press_it("%"))
        self.percentButton.setGeometry(QtCore.QRect(10, 70, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.percentButton.setFont(font)
        self.percentButton.setObjectName("percentButton")
        self.cButton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda:self.press_it("C"))
        self.cButton.setGeometry(QtCore.QRect(100, 70, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.cButton.setFont(font)
        self.cButton.setObjectName("cButton")
        self.arrowButton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda:self.remove_it())
        self.arrowButton.setGeometry(QtCore.QRect(190, 70, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.arrowButton.setFont(font)
        self.arrowButton.setObjectName("arrowButton")
        self.divideButton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda:self.press_it("/"))
        self.divideButton.setGeometry(QtCore.QRect(280, 70, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.divideButton.setFont(font)
        self.divideButton.setObjectName("divideButton")
        self.eightButton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda:self.press_it("8"))
        self.eightButton.setGeometry(QtCore.QRect(100, 150, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.eightButton.setFont(font)
        self.eightButton.setObjectName("eightButton")
        self.multiplyButton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda:self.press_it("*"))
        self.multiplyButton.setGeometry(QtCore.QRect(280, 150, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.multiplyButton.setFont(font)
        self.multiplyButton.setObjectName("multiplyButton")
        self.sevenButton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda:self.press_it("7"))
        self.sevenButton.setGeometry(QtCore.QRect(10, 150, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.sevenButton.setFont(font)
        self.sevenButton.setObjectName("sevenButton")
        self.nineButton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda:self.press_it("9"))
        self.nineButton.setGeometry(QtCore.QRect(190, 150, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.nineButton.setFont(font)
        self.nineButton.setObjectName("nineButton")
        self.fiveButton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda:self.press_it("5"))
        self.fiveButton.setGeometry(QtCore.QRect(100, 230, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.fiveButton.setFont(font)
        self.fiveButton.setObjectName("fiveButton")
        self.minusButton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda:self.press_it("-"))
        self.minusButton.setGeometry(QtCore.QRect(280, 230, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.minusButton.setFont(font)
        self.minusButton.setObjectName("minusButton")
        self.fourButton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda:self.press_it("4"))
        self.fourButton.setGeometry(QtCore.QRect(10, 230, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.fourButton.setFont(font)
        self.fourButton.setObjectName("fourButton")
        self.sixButton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda:self.press_it("6"))
        self.sixButton.setGeometry(QtCore.QRect(190, 230, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.sixButton.setFont(font)
        self.sixButton.setObjectName("sixButton")
        self.twoButton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda:self.press_it("2"))
        self.twoButton.setGeometry(QtCore.QRect(100, 310, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.twoButton.setFont(font)
        self.twoButton.setObjectName("twoButton")
        self.addButton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda:self.press_it("+"))
        self.addButton.setGeometry(QtCore.QRect(280, 310, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.addButton.setFont(font)
        self.addButton.setObjectName("addButton")
        self.oneButton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda:self.press_it("1"))
        self.oneButton.setGeometry(QtCore.QRect(10, 310, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.oneButton.setFont(font)
        self.oneButton.setObjectName("oneButton")
        self.threeButton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda:self.press_it("3"))
        self.threeButton.setGeometry(QtCore.QRect(190, 310, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.threeButton.setFont(font)
        self.threeButton.setObjectName("threeButton")
        self.zeroButton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda:self.press_it("0"))
        self.zeroButton.setGeometry(QtCore.QRect(100, 390, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.zeroButton.setFont(font)
        self.zeroButton.setObjectName("zeroButton")
        self.equalButton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda:self.math_it())
        self.equalButton.setGeometry(QtCore.QRect(280, 390, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.equalButton.setFont(font)
        self.equalButton.setObjectName("equalButton")
        self.plusMinusButton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda:self.plus_minus_it())
        self.plusMinusButton.setGeometry(QtCore.QRect(10, 390, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.plusMinusButton.setFont(font)
        self.plusMinusButton.setObjectName("plusMinusButton")
        self.decimalButton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda:self.dot_it())
        self.decimalButton.setGeometry(QtCore.QRect(190, 390, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.decimalButton.setFont(font)
        self.decimalButton.setObjectName("decimalButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 371, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    # remove character
    def remove_it(self):
        # grab whats on the screen already
        screen = self.outPutLabel.text()
        # remove last item in list/string
        screen = screen[:-1]
        # output back to the screen
        self.outPutLabel.setText(screen) 

    # add a decimal
    def dot_it(self):
        # grab whats on the screen already
        screen = self.outPutLabel.text()
        
        if screen[-1] == ".":
            pass
        else: 
           self.outPutLabel.setText(f'{screen}.') 

    # Math operators
    def math_it(self):
        # grab whats on the screen already
        screen = self.outPutLabel.text()
        try:
            # do the math
            answer = eval(screen)
            self.outPutLabel.setText(str(answer))
        except:
            self.outPutLabel.setText("ERROR ._.")


    # change from positive/negative
    def plus_minus_it(self):
        # grab whats on the screen already
        screen = self.outPutLabel.text()
        if "-" in screen:
            self.outPutLabel.setText(screen.replace("-", "")) 
        else: 
            self.outPutLabel.setText(f'-{screen}') 

    def press_it(self, pressed):
        if pressed == "C":
            self.outPutLabel.setText("0")
        else:
            # Check to see if starts with zero and delete the zero 
            if self.outPutLabel.text() == "0":
                self.outPutLabel.setText("")
            # Concatenate the pressed buton with what was there already
            self.outPutLabel.setText(f'{self.outPutLabel.text()}{pressed}')

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calculator"))
        self.outPutLabel.setText(_translate("MainWindow", "0"))
        self.percentButton.setText(_translate("MainWindow", "%"))
        self.cButton.setText(_translate("MainWindow", "C"))
        self.arrowButton.setText(_translate("MainWindow", "<<"))
        self.divideButton.setText(_translate("MainWindow", "/"))
        self.eightButton.setText(_translate("MainWindow", "8"))
        self.multiplyButton.setText(_translate("MainWindow", "X"))
        self.sevenButton.setText(_translate("MainWindow", "7"))
        self.nineButton.setText(_translate("MainWindow", "9"))
        self.fiveButton.setText(_translate("MainWindow", "5"))
        self.minusButton.setText(_translate("MainWindow", "-"))
        self.fourButton.setText(_translate("MainWindow", "4"))
        self.sixButton.setText(_translate("MainWindow", "6"))
        self.twoButton.setText(_translate("MainWindow", "2"))
        self.addButton.setText(_translate("MainWindow", "+"))
        self.oneButton.setText(_translate("MainWindow", "1"))
        self.threeButton.setText(_translate("MainWindow", "3"))
        self.zeroButton.setText(_translate("MainWindow", "0"))
        self.equalButton.setText(_translate("MainWindow", "="))
        self.plusMinusButton.setText(_translate("MainWindow", "+/-"))
        self.decimalButton.setText(_translate("MainWindow", "."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
